apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  labels:
    deploy: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
        role: web
    spec:
      containers:
        - image: "registryuyt1849.azurecr.io/tripviewer:1.0"
          imagePullPolicy: Always
          name: tripviewer
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          env:
            - name: TRIPS_API_ENDPOINT
              value: "http://10.0.185.150"
            - name: USERPROFILE_API_ENDPOINT
              value: "http://10.0.16.206"
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
spec:
  type: ClusterIP
  selector:
    app: tripviewer
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
