apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    deploy: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - image: "registryuyt1849.azurecr.io/user:1.0"
          imagePullPolicy: Always
          name: user
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          env:
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: sql-secret
                  key: sql_user
                  optional: false
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-secret
                  key: sql_password
                  optional: false
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: sql-secret
                  key: sql_server
                  optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: https
      port: 443
      targetPort: 8443

