apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-edit
  namespace: api
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "8da7f61f-c527-44db-a6ea-68743691fb1e"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-view
  namespace: web
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "8da7f61f-c527-44db-a6ea-68743691fb1e"
  apiGroup: rbac.authorization.k8s.io
